### ISSUE TITLE
【UI】ui问题沟通

### ISSUE THREAD

**Issue by herrynamed** [sjtu-org/sjtu--#3]
定义：
1.视觉稿：1比1真机大小的psd文件，真机通常指iphone6（宽度750px）
2.素材图片：从视觉稿上切出来的可以投入使用的图片
3.效果图：视觉稿 整体导出的图片，一张图片一个页面

我需要：
1.视觉稿
- psd很大，调整以后再上传很麻烦，建议把所有的效果图导出上传到工作目录，让@SherryWei1218确认以后没问题再上传 psd到工作目录

2.素材图片
- 按现有的效果图，字体不是通用的web字体，建议换成 通用的web字体，极不建议所有字体都用web图片表示，通用的中文字：微软雅黑，黑体，宋体；
- 素材图片如果有透明度要求，导出成png-8，如果无，导出成60%质量的jpg；
- 页面底图建议导出大小小于100kb，素材图片建议导出大小小于50kb
- 具体要切哪些素材图片，需效果图出全，例如下图分享按钮，只需 中间那部分3黑点和线，导出成透明底png
![image](https://user-images.githubusercontent.com/14219429/37919178-c2dfe426-3155-11e8-8717-fa120769fb66.png)

3.交互
- 按钮：定义好focus样式（比如底色，字体颜色）
- 页面元素动画：看@SherryWei1218意见是否必须，如无想法，可后期 考虑添加

4.小程序icon
- 图片格式必须为：png,bmp,jpeg,jpg,gif；不可大于2M；建议使用png格式图片，以保持最佳效果；建议图片尺寸为144px*144px

5.小程序导航栏颜色和导航字体颜色
- 导航栏只能设置纯色，不能设置背景图，导航标题只能设置黑白2色
![image](https://user-images.githubusercontent.com/14219429/37943885-2da70d24-31ac-11e8-8229-15b212baed53.png)

6.转发时的默认封面图

**Comment by WilburJiang** [comment]
视觉稿和效果图只是格式不同，内容相同，图片长宽都是真机大小，不知道这样的理解是否正确？

**Comment by herrynamed** [comment]
嗯，效果图主要用来给你们确认是否ok，视觉稿用来实际开发用

**Comment by SherryWei1218** [comment]
页面元素动画，目前暂时可以不添加
