### ISSUE TITLE
【后端】接口问题以及其他问题

### ISSUE THREAD

**Issue by herrynamed** [sjtu-org/sjtu--#7]
@JuYuqi Qs: 
1.<del>目前看起来我们的图片资源有点多，小程序打包有大小限制，我觉得可以所有图片都走我们的服务器，你开个ftp账号我，划一个目录我放静态资源</del>
<del>2.用户token 每次请求时，你从请求 cookie拿吗？</del>
<del>3.response的code数值按你的来吧： 0正常，其他 错误。</del>
<del>4.小花的这些逻辑我觉得放在服务：
<del>- 存储用户单次收集小花的进度 n/5
<del>- 每收集一朵小花，我传 小花code你，你更新进度和小花状态，且如果小花满了，返回进度和 明信片地址我
接口定义 如下：</del>
<del>![image](https://user-images.githubusercontent.com/14219429/38090176-4fa5612a-3394-11e8-8c37-ae72fed661bc.png)</del>

<del>5.制定一份 学院列表， 学院唯一码 学院名称，我配置在小程序里的 地图中，点击学院，用学院唯一码请求 感恩墙</del>

<del>6./user/login 接口返回请按约定返回正确的字段</del>
![image](https://user-images.githubusercontent.com/14219429/38134689-c4e806c4-3446-11e8-8bd7-f62b89495c31.png)
<del>7.收集小花接口 flower/{flowerId}  ，返回建议加上 collectedNum: Interger, //当前收集到的小花数，taskNum: Interger, //每张明信片所需收集的小花数，为了让数据保持一致，因为这2个都是后端维护的，这个接口应该是get，文档里有误，联调发现 返回 Request method 'GET' not supported</del>

<del>8.获取附近的明信片 postcard/location ，文档里是get，应该是Post，其中有关返回的 name说明有 地点名称:如果不在范围内，返回为未知，如果地点不再范围内，应该不会作为接口返回吧</del>

<del>9./postcard接口返回的 明信片分页数据是按 以获得的，按产品原型，是需要 按明信片总数来分页的，未得到的，用未知明信片表示，这张占位图片可以 给你，你返回我，也可以我自己 做判断显示</del>
![image](https://user-images.githubusercontent.com/14219429/38241675-6be680ce-3765-11e8-890c-53e4a7c96cc3.png)

10.寄送 明信片接口各字段的 长度限制

11.postcard接口记不太清是否是 按 已获得的来分类了，看返回有 返回未知图片的 url，不知道是不是测试时录入的，注：前端的分页是 按 明信片种类 分页的，我想确认下 后端的分页对象是啥，好知道 翻页时是否需要去请求接口，上次 确定了，忘了不好意思

**Comment by JuYuqi** [comment]
2、token从request的header里拿
3、response的code数值是200正常，其他 错误。
4、
![image](https://user-images.githubusercontent.com/16338708/38120888-45b9871c-33fe-11e8-8e7f-a4275347448a.png)
现在后端的返回格式是这样的，花朵状态返回的是一个List<Boolean>，没有uniqueCode，默认按照0~9来对应小花，collectProgress我会分成collectedNum和maxNum来返回，分别表示已收集数目和最大数目
5、学院也是一样，用序号对应不同的学院，具体学院列表由卿来整理一下

**Comment by herrynamed** [comment]
2. token从header拿，是cookie吗，还是 我要设置header头
4. 我未说清楚，小花集齐兑明信片整套逻辑我都想放到后端，后端保持 花 和 个人所得明信片的数据一致性，小花要有 uniqueCode 的原因是，我采集小花，用 uniqueCode来更新小花状态，用序号0 ~9，和unqieCode是一样的吧
5.序号对应学院也行，只要需要可以唯一表示一所学校
![image](https://user-images.githubusercontent.com/14219429/38122103-968f4616-3405-11e8-889e-c317f4905704.png)

**Comment by JuYuqi** [comment]
6、接口的host为www.shenqingtong.com/sjtuorg

**Comment by herrynamed** [comment]
![image](https://user-images.githubusercontent.com/14219429/38344548-b7b776f4-38bc-11e8-9ea3-0059747d933e.png)
![image](https://user-images.githubusercontent.com/14219429/38344553-bf666f22-38bc-11e8-9082-6d1e66c26b0e.png)
