### ISSUE TITLE
【测试】 测试问题汇总

### ISSUE THREAD

**Issue by herrynamed** [sjtu-org/sjtu--#9]
格式如下（demo）：
1.【优化】 花朵样式颜色 要变浅
2.【bug】明信片列表 加载不出来

1.

**Comment by WilburJiang** [comment]
<del>1.【bug】有未知明信片可寄送，这是因为这张卡是我很早之前收集到的，所以才会有的么？</del>
![img_3815a0069e9f-1](https://user-images.githubusercontent.com/29849486/38384899-f286ca9c-3942-11e8-97b0-ecb67434ca46.jpeg)
![img_ace78d0e303f-1](https://user-images.githubusercontent.com/29849486/38384909-f797f27c-3942-11e8-9755-0b46b1b28cb8.jpeg)
<del>2.【优化】明信片墙多次使用之后，再次使用需要点击返回键，手动返回主界面，才会显示如图界面</del>
![img_6fda26fded5f-1](https://user-images.githubusercontent.com/29849486/38385155-bf8523b8-3943-11e8-8c1e-a911088da5c7.jpeg)
<del>完全退出小程序重新loading之后，明信片墙又可以正常使用，多次使用后依然出现前述问题，这是缓存的缘故么？</del>
<del>3. 【bug】可寄送空白明信片内容，老师和内容应该是必填项。</del>
![img_ee960b11cd08-1](https://user-images.githubusercontent.com/29849486/38385582-d3bab8e2-3944-11e8-9f3f-93f2f5583e5a.jpeg)
<del>4. 【优化】学院名字太长导致换行，需要修改学院名字以适合框，最多11个字</del>
![img_10c52fa86f59-1](https://user-images.githubusercontent.com/29849486/38385619-e84bcb0c-3944-11e8-9a42-d44cbc31467a.jpeg)
<del>5. 【优化】缺少直接退出小程序重新加载的按键，还是说本身就是缓存一次。可否使用左上角系统自带的</del>
![img_949ecfcf63ce-1](https://user-images.githubusercontent.com/29849486/38385832-87e98e42-3945-11e8-9638-12188545471a.jpeg)

**Comment by Seraphimmmmm** [comment]
<del>5.信封气泡毛毛躁躁看着难受</del>
![_20180406110706](https://user-images.githubusercontent.com/37732829/38401868-d8a87aa6-398a-11e8-98b1-1e59e03de39e.jpg)
<del>6.关闭button建议在提示框上一层，不然重合区会很别扭</del>
![_201804061107062](https://user-images.githubusercontent.com/37732829/38401897-0e55f49e-398b-11e8-86d4-4df6641b3354.jpg)
<del>7.感恩墙可以用滑动方式进入第4,5页</del>
![_201804061107061](https://user-images.githubusercontent.com/37732829/38402011-e32b097a-398b-11e8-957e-8188be594082.jpg)

8.【优化】
<del>i，在“附近的明信片”窗口不能关闭或返回，总之就是一直僵在这个界面，如果返回会退出小程序；</del>
<del>ii，由于明信片可以选择不填写直接返回，为了防止大家只玩不写，要不要增加一个第一次获得明信片的时候必须填写的功能（不可关闭）？
iii，写完祝福语寄送后要不要来个提示：“寄送成功”？？</del>

<del>9.感恩墙的颜色不对啊喂！！！</del>
![_20180406112558](https://user-images.githubusercontent.com/37732829/38402339-16e86044-398e-11e8-8dbb-273f3f996914.jpg)
应该是：
![_20180406112702](https://user-images.githubusercontent.com/37732829/38402341-1cb7c1c2-398e-11e8-805c-7d8c97e38acb.png)
（跟查看详情时候的黄色窗口一样）

**Comment by WilburJiang** [comment]
<del>10. 【bug】这里无论点击“是”还是“否”都无法退出</del>
![wechatimg737](https://user-images.githubusercontent.com/29849486/38423998-379f959c-39e2-11e8-9936-c7df015740c8.jpeg)
<del>11. 【bug】从明信片墙点开明信片后，点击写祝福，会自动填充上次填写的内容；</del>
![wechatimg0](https://user-images.githubusercontent.com/29849486/38424092-886fa02a-39e2-11e8-979d-03d0626e2bc7.jpeg)
12. 【bug】已收集的明信片，实地收集的时候，显示如下，但是“收集”button点击无效。（猜测：是因为这些明信片是我通过小花抽取到的么？）
![wechatimg739](https://user-images.githubusercontent.com/29849486/38424149-b1d803bc-39e2-11e8-90a0-cf6d2a472d43.jpeg)
@herrynamed @JuYuqi
